FROM hashicorp/vault:1.14

EXPOSE 8200

# Définition des variables d'environnement pour Vault
ENV VAULT_ADDR=http://0.0.0.0:8200
ENV VAULT_TOKEN="hvs.YSFOyujJCqXHwgGDKtdveGCi"
ENV VAULT_DATA_PATH=/vault/file

# Commande par défaut pour exécuter Vault en mode serveur
CMD ["server", "-dev"]